spring.application.name=backend

# Use H2 (No password needed!)
spring.datasource.url=jdbc:h2:mem:votingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# This allows you to see the database in your browser at http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update